services:
  api:
    build: ./fastapi_app
    ports:
      - "${FASTAPI_PORT}:8080"

  streamlit:
    build: ./streamlit_app
    ports:
      - "${STREAMLIT_PORT}:8501"
    environment:
      API_URL: http://api:8080
